kind: pipeline
name: amd64_ub2004_distro

platform:
  os: linux
  arch: amd64

steps:
- name: build_and_test
  image: amd64/ubuntu:20.04
  environment:
    POCL_CACHE_DIR: /tmp/cache
    POCL_MAX_PTHREAD_COUNT: 2
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt upgrade -y
  - apt install -y libpython3-dev python3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-12-dev libclang-cpp12-dev clang-12 llvm-12-dev make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils
  - mkdir build
  - cd build
  - cmake -DKERNELLIB_HOST_CPU_VARIANTS=distro -DPOCL_ICD_ABSOLUTE_PATH=OFF -DENABLE_POCL_BUILDING=OFF -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja install
  - clinfo
  - rm CTestCustom.cmake
  - ctest -j32 --output-on-failure -L internal

---
kind: pipeline
name: arm64_ub1804_llvm6

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_test
  image: arm64v8/ubuntu:18.04
  environment:
    POCL_CACHE_DIR: /tmp/cache
    POCL_MAX_PTHREAD_COUNT: 2
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt upgrade -y
  - apt install -y libpython3-dev python3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-6.0-dev clang-6.0 llvm-6.0 make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils
  - mkdir build
  - cd build
  - cmake -DDEVELOPER_MODE=ON -DLLC_HOST_CPU=thunderx -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja install
  - clinfo
  - ctest -j32 --output-on-failure -L internal

---
kind: pipeline
name: arm64_ub1804_llvm9

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_test
  image: arm64v8/ubuntu:18.04
  environment:
    POCL_BUILDING: 1
    POCL_CACHE_DIR: /tmp/cache
    POCL_MAX_PTHREAD_COUNT: 2
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt upgrade -y
  - apt install -y libpython3-dev python3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-9-dev clang-9 llvm-9 make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils
  - mkdir build
  - cd build
  - cmake -DDEVELOPER_MODE=ON -DLLC_HOST_CPU=thunderx -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja install
  - clinfo
  - ctest -j32 --output-on-failure -L internal

---
kind: pipeline
name: arm64_ub2004_llvm10

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_test
  image: arm64v8/ubuntu:20.04
  environment:
    POCL_BUILDING: 1
    POCL_CACHE_DIR: /tmp/cache
    POCL_MAX_PTHREAD_COUNT: 2
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt upgrade -y
  - apt install -y libpython3-dev python3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-10-dev libclang-cpp10-dev clang-10 llvm-10-dev make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils
  - mkdir build
  - cd build
  - cmake -DDEVELOPER_MODE=ON -DLLC_HOST_CPU=thunderx -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja install
  - clinfo
  - ctest -j32 --output-on-failure -L internal

---
kind: pipeline
name: arm64_ub2004_llvm12

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_test
  image: arm64v8/ubuntu:20.04
  environment:
    POCL_BUILDING: 1
    POCL_CACHE_DIR: /tmp/cache
    POCL_MAX_PTHREAD_COUNT: 2
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt upgrade -y
  - apt install -y libpython3-dev python3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-12-dev libclang-cpp12-dev clang-12 llvm-12-dev make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils
  - mkdir build
  - cd build
  - cmake -DDEVELOPER_MODE=ON -DLLC_HOST_CPU=thunderx -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja install
  - clinfo
  - ctest -j32 --output-on-failure -L internal
